--------------------------------------------------------
-- Archivo creado  - domingo-octubre-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USUARIO" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"EDAD" NUMBER(*,0), 
	"PROFESION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USUARIO" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"EDAD" NUMBER(*,0), 
	"PROFESION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USUARIO
SET DEFINE OFF;
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('0','JHOANA MARTA','35','FUNCIONARIO');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('1','MARTA SANDRA','38','ADMINISTRATIVO');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('2','FELIPE JULIAN','39','ESTUDIANTE');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('3','DAYANA JULIAN','23','ADMINISTRATIVO');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('6','DANIEL MARCELA','27','DOCENTE');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('5','MARCELA MARCELA','24','ESTUDIANTE');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('7','SANDRA MACHADO','23','DOCENTE');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('12','DAYANA CETINA','29','ESTUDIANTE');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('16','DANIELA BRAVO','30','FUNCIONARIO');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('20','JOHANA CETINA','29','FUNCIONARIO');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('21','MARCELA VALVUENA','23','ESTUDIANTE');
Insert into SYSTEM.USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('24','JHOANA LOPEZ','26','ADMINISTRATIVO');
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."USUARIO_PK" ON "SYSTEM"."USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USUARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
