/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ControladorORA;
import Control.ControladorSQLS;
import Control.ImageTableModel;
import Control.Imagenes;
import Modelo.DTO.EstudianteDTO;
import Modelo.DTO.LogicaDBDTO;
import Modelo.DTO.UsuarioDTO;
import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author milto
 */
public class InterfazP extends javax.swing.JFrame {

    ControladorORA objControlORA;
    ControladorSQLS objControlSQLS;

    /**
     * Creates new form InterfazP
     */
    public InterfazP() {
        initComponents();
        setLocationRelativeTo(null);
        objControlORA = new ControladorORA();
        objControlSQLS = new ControladorSQLS();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRuta = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtprofesion = new javax.swing.JTextField();
        btnCargarFoto = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        cmbDB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnCommit = new javax.swing.JButton();
        btnRollBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtNum3 = new javax.swing.JTextField();
        txtrest1 = new javax.swing.JTextField();
        txtNum4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtCodSQLS = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtPromSQLS = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtrest2 = new javax.swing.JTextField();
        btnLimpiarSQLS = new javax.swing.JButton();
        btnLimpiarORA = new javax.swing.JButton();

        lblRuta.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Aplicación Oracle - SQL Server");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("ID :");

        jLabel3.setText("NOMBRE: ");

        jLabel4.setText("EDAD : ");

        jLabel5.setText("PROFESION : ");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        btnCargarFoto.setText("CARGAR");
        btnCargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarFotoActionPerformed(evt);
            }
        });

        lblFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtprofesion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtprofesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarFoto)
                .addGap(6, 6, 6))
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 580, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnInsertar)
                .addGap(42, 42, 42)
                .addComponent(btnActualizar)
                .addGap(40, 40, 40)
                .addComponent(btnEliminar)
                .addGap(34, 34, 34)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 480, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "EDAD", "PROFESIÓN", "FOTO"
            }
        ));
        tabla_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_usuarios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 580, 200));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "Oracle", "SQL Server" }));
        cmbDB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDBItemStateChanged(evt);
            }
        });
        cmbDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDBActionPerformed(evt);
            }
        });

        jLabel6.setText("Motor de base de datos :  ");

        btnCommit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Commit.jpg"))); // NOI18N
        btnCommit.setToolTipText("COMMIT");
        btnCommit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCommit.setIconTextGap(0);
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });

        btnRollBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Rollback.jpg"))); // NOI18N
        btnRollBack.setIconTextGap(0);
        btnRollBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(cmbDB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRollBack, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRollBack, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 480, 40));

        jTabbedPane2.addTab("CRUD", jPanel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Funciones y Procedimientos");

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("COD:  ");

        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre : ");

        jLabel17.setText("Número 1:");

        jButton4.setText("COMPARAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtrest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrest1ActionPerformed(evt);
            }
        });

        txtNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum4ActionPerformed(evt);
            }
        });

        jLabel18.setText("Número 2 : ");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtrest1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(txtrest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );

        jLabel11.setText("ORACLE");

        jLabel12.setText("SQL SERVER");

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("COD: ");

        jButton2.setText("CONSULTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Promedio: ");

        txtPromSQLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromSQLSActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setText("Número 1:");

        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Número 2 : ");

        jButton3.setText("COMPARAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtrest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrest2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtPromSQLS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodSQLS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton2))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtrest2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCodSQLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPromSQLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(txtrest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        btnLimpiarSQLS.setText("LIMPIAR");
        btnLimpiarSQLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSQLSActionPerformed(evt);
            }
        });

        btnLimpiarORA.setText("LIMPIAR");
        btnLimpiarORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarORAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnLimpiarSQLS)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnLimpiarORA)
                        .addGap(35, 35, 35))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarORA)
                .addGap(4, 4, 4)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarSQLS))
        );

        jTabbedPane2.addTab("F & P", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        boolean respuesta = false;
        if (validarCampos()) {
            JOptionPane.showMessageDialog(this, "TODOS LOS CAMPOS SON OBLIGATORIOS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else if (this.cmbDB.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "DEBE ESCOGER UN MOTOR DE BASE DE DATOS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            UsuarioDTO user = new UsuarioDTO();
            user.setId(Integer.valueOf(this.txtid.getText()));
            user.setNombre(this.txtnombre.getText());
            user.setEdad(Integer.valueOf(this.txtedad.getText()));
            user.setProfesion(this.txtprofesion.getText());
            user.setFoto(new File(lblRuta.getText()));

            switch (this.cmbDB.getSelectedIndex()) {
                case 1:
                    respuesta = objControlORA.insertarUsuario(user);
                    break;
                case 2:
                    respuesta = objControlSQLS.insertarUsuario(user);
                    break;
                default:
                    break;
            }
            if (respuesta) {
                JOptionPane.showMessageDialog(this, "USUARIO INSERTADO CORRECTAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ERROR AL INSERTAR USUARIO CON ID " + user.getId(), "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            }
            if (this.cmbDB.getSelectedItem().toString().equals("Oracle")) {
                this.listarUsuarios("Oracle");
            } else {
                this.listarUsuarios("SQL Server");
            }
        }

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        boolean respuesta = false;
        if (this.txtid.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO ID ES OBLIGATORIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            UsuarioDTO user = new UsuarioDTO();
            user.setId(Integer.valueOf(this.txtid.getText()));
            switch (this.cmbDB.getSelectedIndex()) {
                case 1:
                    respuesta = objControlORA.eliminarUsuario(user);
                    break;
                case 2:
                    respuesta = objControlSQLS.eliminarUsuario(user);
                    break;
                default:
                    break;
            }

            if (respuesta) {
                JOptionPane.showMessageDialog(this, "USUARIO ELIMINADO CORRECTAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ERROR AL ELIMINAR USUARIO CON ID " + user.getId(), "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            }

            if (this.cmbDB.getSelectedItem().toString().equals("Oracle")) {
                this.listarUsuarios("Oracle");
            } else {
                this.listarUsuarios("SQL Server");
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDBActionPerformed

    private void cmbDBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDBItemStateChanged

        if (this.cmbDB.getSelectedItem().toString().equals("Oracle")) {
            this.listarUsuarios("Oracle");
        } else {
            this.listarUsuarios("SQL Server");
        }

    }//GEN-LAST:event_cmbDBItemStateChanged

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        if (objControlORA.aplicarTransacionORA()) {
            JOptionPane.showMessageDialog(this, "COMMIT REALIZADO CORRECTAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "ERROR AL REALIZAR COMMIT", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCommitActionPerformed

    private void btnRollBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollBackActionPerformed
        if (objControlORA.descartarTransacionORA()) {
            JOptionPane.showMessageDialog(this, "ROLLBACK REALIZADO CORRECTAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "ERROR AL REALIZAR ROLLBACK", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRollBackActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        boolean respuesta = false;
        if (this.validarCampos()) {
            JOptionPane.showMessageDialog(this, "TODOS LOS CAMPOS SON OBLIGATORIOS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else if (this.cmbDB.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "DEBE ESCOGER UN MOTOR DE BASE DE DATOS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            UsuarioDTO user = new UsuarioDTO();
            user.setId(Integer.valueOf(this.txtid.getText()));
            user.setNombre(this.txtnombre.getText());
            user.setEdad(Integer.valueOf(this.txtedad.getText()));
            user.setProfesion(this.txtprofesion.getText());
            //user.setFoto(new File(lblRuta.getText()));
            if (!this.lblRuta.getText().isBlank()) {
                user.setFotoIcon((ImageIcon) this.lblFoto.getIcon());
            } else {
                user.setFotoIcon(null);
            }

            switch (this.cmbDB.getSelectedIndex()) {
                case 1:
                    respuesta = objControlORA.modificarUsuario(user);
                    break;
                case 2:
                    respuesta = objControlSQLS.modificarUsuario(user);
                    break;
                default:
                    break;
            }
            if (respuesta) {
                JOptionPane.showMessageDialog(this, "USUARIO ACTUALIZADO CORRECTAMENTE", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ERROR AL ACTUALIZAR USUARIO CON ID " + user.getId(), "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            }
            if (this.cmbDB.getSelectedItem().toString().equals("Oracle")) {
                this.listarUsuarios("Oracle");
            } else {
                this.listarUsuarios("SQL Server");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean respuesta = false;
        if (this.txtid.getText().isBlank() || this.cmbDB.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "EL CAMPO ID Y EL MOTOR DE BASE DE DATOS ES OBLIGATORIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            UsuarioDTO user = new UsuarioDTO();
            user.setId(Integer.valueOf(this.txtid.getText()));
            System.out.println(this.cmbDB.getSelectedIndex());
            switch (this.cmbDB.getSelectedIndex()) {
                case 1:
                    user = objControlORA.buscarUsuario(user);
                    break;
                case 2:
                    user = objControlSQLS.buscarUsuario(user);
                    break;
                default:
                    break;
            }
            //System.out.println(Integer.valueOf(user.getId()));
            if (user != null) {
                ArrayList listU = new ArrayList<UsuarioDTO>();
                listU.add(user);
                this.llenarTabla(listU);
                
                /*this.tabla_usuarios.setDefaultRenderer(Object.class, new ImageTableModel());
                DefaultTableModel model = (DefaultTableModel) this.tabla_usuarios.getModel();
                //DefaultTableModel model = (DefaultTableModel) this.tabla_usuarios.getModel();
                model.setRowCount(0);
                Object[] array = new Object[model.getColumnCount()];

                array[0] = user.getId();
                array[1] = user.getNombre();
                array[2] = user.getEdad();
                array[3] = user.getProfesion();
                
                array[4] = user.getFoto();
                model.addRow(array);*/
            } else {
                JOptionPane.showMessageDialog(this, "USUARIO NO ENCONTRADO ", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tabla_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_usuariosMouseClicked
        int seleccion = this.tabla_usuarios.getSelectedRow();
        if (seleccion >= 0) {
            this.txtid.setText(String.valueOf(this.tabla_usuarios.getValueAt(seleccion, 0)));
            this.txtnombre.setText((String) this.tabla_usuarios.getValueAt(seleccion, 1));
            this.txtedad.setText(String.valueOf(this.tabla_usuarios.getValueAt(seleccion, 2)));
            this.txtprofesion.setText((String) this.tabla_usuarios.getValueAt(seleccion, 3));
            JLabel lblIcon = (JLabel) this.tabla_usuarios.getValueAt(seleccion, 4);
            this.lblFoto.setIcon(lblIcon.getIcon());
            this.lblRuta.setText("");
        }
    }//GEN-LAST:event_tabla_usuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtCod.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO ID ES OBLIGATORIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            String nombre;
            float promedio;
            EstudianteDTO estudiante = new EstudianteDTO();
            estudiante.setCodigo(Integer.valueOf(this.txtCod.getText()));
            estudiante = objControlORA.func_obtenerNomEstudiante(estudiante);
            txtNombre.setText(estudiante.getNombres());
        }

        //promedio = objControlORA
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtCodSQLS.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "EL CAMPO DEL CÓDIGO ES OBLIGATORIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            float promedio;
            EstudianteDTO estudiante = new EstudianteDTO();
            estudiante.setCodigo(Integer.valueOf(this.txtCodSQLS.getText()));
            promedio = objControlSQLS.func_obtenerPromedio(estudiante);
            this.txtPromSQLS.setText(String.valueOf(promedio));
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPromSQLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromSQLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromSQLSActionPerformed

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtNum1.getText().isBlank() || txtNum2.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "SE DEBEN INGRESAR AMBOS NÚMEROS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            int num1, num2;
            String respuesta;
            num1 = (Integer.valueOf(this.txtNum1.getText()));
            num2 = (Integer.valueOf(this.txtNum2.getText()));
            LogicaDBDTO objLogic = new LogicaDBDTO();
            objLogic.setNum1(num1);
            objLogic.setNum2(num2);
            objLogic = objControlSQLS.func_compararDosNumeros(objLogic);
            if (objLogic.getRespString().equals("iguales")) {
                txtrest2.setText("Los números son iguales");
            } else {
                txtrest2.setText("El número " + objLogic.getRespString() + " es el mayor");
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtrest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrest2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txtNum4.getText().isBlank() || txtNum3.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "SE DEBEN INGRESAR AMBOS NÚMEROS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            int num1, num2;
            String respuesta;
            num1 = (Integer.valueOf(this.txtNum4.getText()));
            num2 = (Integer.valueOf(this.txtNum3.getText()));
            LogicaDBDTO objLogic = new LogicaDBDTO();
            objLogic.setNum1(num1);
            objLogic.setNum2(num2);
            objLogic = objControlORA.compararDosNumeros(objLogic);
            if (objLogic.getRespString().equals("iguales")) {
                txtrest1.setText("Los números son iguales");
            } else {
                txtrest1.setText("El número " + objLogic.getRespString() + " es el mayor");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtrest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrest1ActionPerformed

    private void txtNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum4ActionPerformed

    private void btnLimpiarORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarORAActionPerformed
        this.limpiarORA();
    }//GEN-LAST:event_btnLimpiarORAActionPerformed

    private void btnLimpiarSQLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSQLSActionPerformed
        this.limpiarSQLS();
    }//GEN-LAST:event_btnLimpiarSQLSActionPerformed

    private void btnCargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarFotoActionPerformed

        try {
            JFileChooser jfile = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Jpg", "JPEG", "JPG", "jpeg", "png", "PNG");
            jfile.setAcceptAllFileFilterUsed(false);
            jfile.setFileFilter(filtro);
            jfile.setDialogTitle("SELECCIONAR FOTO");

            File fichero;
            if (jfile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                fichero = jfile.getSelectedFile();
                this.lblFoto.setIcon(Imagenes.ConverImagen(lblFoto, fichero.getPath()));
                this.lblRuta.setText(fichero.toString());
            }

        } catch (NullPointerException e) {
            //JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCargarFotoActionPerformed

    void limpiarORA() {
        this.txtCod.setText("");
        this.txtNombre.setText("");
        this.txtNum3.setText("");
        this.txtNum4.setText("");
        this.txtrest1.setText("");
    }

    void limpiarSQLS() {
        this.txtCodSQLS.setText("");
        this.txtPromSQLS.setText("");
        this.txtNum1.setText("");
        this.txtNum2.setText("");
        this.txtrest2.setText("");
    }

    boolean validarCampos() {
        return (this.txtid.getText().isBlank() || this.txtnombre.getText().isBlank() || this.txtedad.getText().isBlank() || this.txtprofesion.getText().isBlank());
    }

    void listarUsuarios(String db) {
        List<UsuarioDTO> usuarios = null;
        switch (db) {
            case "Oracle":
                usuarios = objControlORA.consultarUsuarios();
                this.btnCommit.setVisible(true);
                this.btnRollBack.setVisible(true);
                System.err.println("ORACLE");
                break;
            case "SQL Server":
                usuarios = objControlSQLS.consultarUsuarios();
                this.btnCommit.setVisible(false);
                this.btnRollBack.setVisible(false);
                System.err.println("SQL SERVER");
                break;
            default:
                System.err.println("NO SE HA ESCOGIDO EL MOTOR DE BASE DE DATOS");
                break;
        }
        if (usuarios != null) {
            this.llenarTabla(usuarios);
        }
    }

    void llenarTabla(List<UsuarioDTO> usuarios) {

        this.tabla_usuarios.setDefaultRenderer(Object.class, new ImageTableModel());
        DefaultTableModel model = (DefaultTableModel) this.tabla_usuarios.getModel();
        model.setNumRows(0);

        Object[] array = new Object[model.getColumnCount()];
        for (UsuarioDTO usuario : usuarios) {
            array[0] = usuario.getId();
            array[1] = usuario.getNombre();
            array[2] = usuario.getEdad();
            array[3] = usuario.getProfesion();
            usuario.setFotoIcon(Imagenes.ConverImagen(60, 90, usuario.getFotoIcon()));
            array[4] = new JLabel(usuario.getFotoIcon());
            model.addRow(array);
            //System.out.println("ALTURA: "+usuario.getFotoIcon().getIconHeight());
            this.tabla_usuarios.setRowHeight(70);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarFoto;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiarORA;
    private javax.swing.JButton btnLimpiarSQLS;
    private javax.swing.JButton btnRollBack;
    private javax.swing.JComboBox<String> cmbDB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JTable tabla_usuarios;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCodSQLS;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum3;
    private javax.swing.JTextField txtNum4;
    private javax.swing.JTextField txtPromSQLS;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprofesion;
    private javax.swing.JTextField txtrest1;
    private javax.swing.JTextField txtrest2;
    // End of variables declaration//GEN-END:variables
}
