--ORACLE
CREATE TABLE USUARIO 
(
  ID NUMBER NOT NULL 
, NOMBRE VARCHAR2(100) 
, EDAD NUMBER 
, PROFESION VARCHAR2(100) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


--SQLSERVER
CREATE TABLE USUARIO 
(
  ID int NOT NULL 
, NOMBRE VARCHAR(100) 
, EDAD INT 
, PROFESION VARCHAR(100) 
,  PRIMARY KEY 
  (
    ID
  )
  
);

--INSERTS

Insert into USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('0','JHOANA MARTA','35','FUNCIONARIO');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('1','MARTA SANDRA','38','ADMINISTRATIVO');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('2','FELIPE JULIAN','39','ESTUDIANTE');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('3','DAYANA JULIAN','23','ADMINISTRATIVO');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('6','DANIEL MARCELA','27','DOCENTE');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('5','MARCELA MARCELA','24','ESTUDIANTE');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('7','SANDRA MACHADO','23','DOCENTE');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('12','DAYANA CETINA','29','ESTUDIANTE');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('16','DANIELA BRAVO','30','FUNCIONARIO');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('20','JOHANA CETINA','29','FUNCIONARIO');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('21','MARCELA VALVUENA','23','ESTUDIANTE');
Insert into  USUARIO (ID,NOMBRE,EDAD,PROFESION) values ('24','JHOANA LOPEZ','26','ADMINISTRATIVO');
